### ISSUE TITLE
Exploration: How we can run GPU workloads in LXC

### ISSUE THREAD

**Issue by misohu** [canonical/data-science-stack#18]
### Why it needs to get done

For the DSS we want to execute containers. As an alternative to Docker LXC comes into play. 

### What needs to get done

- Find out how to run GPU workloads with LXC
- Find out how to run Docker containers in LXC 
- Research how run GPU workloads with IntelGPU devices

### When is the task considered done

We have clear understanding if LXC is our way to deploy GPU workloads.

**Comment by misohu** [comment]
Docker and LXC (Linux Containers) are both containerization technologies, but they have different implementations and are designed for different use cases. Docker uses a higher-level abstraction and provides a platform for developing, shipping, and running applications in containers. LXC, on the other hand, is a lower-level containerization technology that provides a lightweight virtualization solution for running multiple Linux distributions on a single host.

While Docker uses its own container runtime (containerd or dockerd), LXC has its own set of tools, including lxc-start and lxc-create. Generally, Docker containers are not directly compatible with LXC containers because Docker uses a different approach to containerization.

However, it is possible to run Docker inside an LXC container with some additional configuration. This involves starting the LXC container with certain privileges to allow Docker to function correctly. Keep in mind that running Docker inside an LXC container adds an additional layer of abstraction and may have some limitations compared to running Docker directly on the host machine.

Here are some high-level steps you might follow to run Docker inside an LXC container:

1. Install LXC: Ensure that LXC is installed on your system.
2. Create an LXC Container: Create a new LXC container using the lxc-create command.
3. Start the LXC Container: Start the LXC container using the lxc-start command.
4. Install Docker Inside the LXC Container: Once the LXC container is running, you can enter it and install Docker as you would on a regular Linux system.
5. Configure Docker to Run Inside the LXC Container: Ensure that Docker is configured to work within the LXC environment. You might need to adjust Docker settings or grant certain privileges.

**Comment by misohu** [comment]
After talking to LXD team (notes from the written conversation [here ](https://chat.canonical.com/canonical/pl/ez3fch51e78188f4meqao1s4ua)). These are the conclusions:
- There is no direct way to JUST run docker images with our gou workloads in LXC. The proposed solution by the team was to install docker inside LXC instance which seems counter intuitive. 
- There currently no direct support for intelGPU in LXC (the reason why there support Nvidia is because their drivers are supported in containers more bellow). 
- There is an option to run Nvidia workloads in LXC with the approach they call GPU passthrough (please beware of the misleading name as this is not PCI passthrough).  In this scenario we instead have the host setup with all needed drivers and only pass the resulting device nodes to the container. Containers are basically running same driver as the host. I was able to replicate the setup with [this tutorial](https://ubuntu.com/blog/nvidia-cuda-inside-a-lxd-container).

### Conclusions 
After discussions with the LXD team and trying some of their tutorials looks like LXC containers are ok for GPU workloads. The setup is quite easy and it works. The problem is that there is no direct support for docker containers. We would need to handle the transition from Docker to LXC. The proposed way of LXC team was to install Docker in the LXC machine which is defeating the purpose of using LXC (we want to replace Docker). 

Another problem is with the IntelGPU driver support. After discussions it is clear that there is no direct support for using Intel based GPUs inside LXC containers and there is not planned effort for that. We basically need similar passthrough for IntelGPU as they do for Nvidia devices.

**Comment by DnPlas** [comment]
> There currently no direct support for intelGPU in LXC (the reason why there support Nvidia is because their drivers are supported in containers more bellow).

Based on what I have read and on the LXD team, it sounds like the GPU passtrough could work with any GPU whose drivers are designed in a way to make them possible to be used by containers. 

I think we then need to know which Intel GPUs are we interested in supporting to understand which GPU drivers are required. Then it would be easier to understand if the Intel GPU drivers are also designed in a way in which we can use them in containers. From what I have read [here](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_xpu.md#install-via-docker-container) it could be possible. 

> There is no direct way to JUST run docker images with our gpu workloads in LXC. The proposed solution by the team was to install docker inside LXC instance which seems counter intuitive.

Did the team suggested something else? Do we now have to create our own container images with projects like [distrobuilder](https://github.com/lxc/distrobuilder)?

Just for reference, here are some docs that talk about [devices](https://documentation.ubuntu.com/lxd/en/latest/reference/devices/) and [configuring devices](https://documentation.ubuntu.com/lxd/en/latest/howto/instances_configure/#instances-configure-devices).

**Comment by misohu** [comment]
Thanks @DnPlas,




> I think we then need to know which Intel GPUs are we interested in supporting to understand which GPU drivers are required. Then it would be easier to understand if the Intel GPU drivers are also designed in a way in which we can use them in containers. From what I have read [here](https://github.com/intel/intel-extension-for-tensorflow/blob/main/docs/install/install_for_xpu.md#install-via-docker-container) it could be possible.

Agree lets make a list of intel devices which we want to support and then research driver options (This list will be helpful even if we don't go with LXC)



> Did the team suggested something else? Do we now have to create our own container images with projects like [distrobuilder](https://github.com/lxc/distrobuilder)?

Yes besides installing Docker in LXC or creating own LXC instances I think there is no other option. The distrobuilder is nice but I believe DSS wants to support functionality of "bring your own image" where users will use their own Docker images.
