### ISSUE TITLE
Create a CI for testing the DSS snap

### ISSUE THREAD

**Issue by DnPlas** [canonical/data-science-stack#26]
### Why it needs to get done

We need a way of testing the DSS snap on `pull request` and `push`.

### What needs to get done

Have a Github workflow that runs testing (unit and/or integration) on the snap. The testing that has to be done is ensuring the snap builds and the CLI commands work and don't return a non-zero exit code.

Please refer to #23 for more details on what can be leveraged (actions, reusable code, etc.)

### When is the task considered done

When there is a workflow that automatically runs the sanity tests described above.

**Comment by misohu** [comment]
We want to have integration tests for snap similar to the once we are doing on PRS for dss python library.

**Comment by ca-scribner** [comment]
Do we know what sort of failure modes a snap could expect?  Maybe not being able to access kubernetes, or not shipping with one of the yaml templates?  probably just `dss initialize`, and maybe `dss create ...` and that is good?

Plus, once we have a kubeconfig caching mechanism, test that too?
