### ISSUE TITLE
Implement DSS `create-notebook` command

### ISSUE THREAD

**Issue by DnPlas** [canonical/data-science-stack#31]
### Why it needs to get done

The create-notebook command allows users to create a Jupyter notebook within the DSS environment. Users specify the notebook's name and an image for the notebook. Behind the scenes, the DSS Python library creates a notebook object from a Kubernetes manifest template, using the provided name and image flags. The command waits until the notebook pod is ready and then outputs a link to access the notebook UI. While waiting for the pod, DSS will output the status of the Pod (Creating, Waiting …). This command will fail with an error message if the Pod won’t get created or if it ends with an error.

The command looks like:

```
dss create-notebook --name user-notebook --image kubeflownotebookswg/jupyter-scipy:v1.8.0
```

Whenever a notebook is created dss deploys these Kubernetes objects: 
* Notebook deployment. This notebook will mount the `user-data` PVC which is shared across all notebooks. Additionally, the notebook requires an environment variable `MLFLOW_TRACKING_URI` set with a URL pointing to the MLflow server to be able to connect.
* Notebook ClusterIP service, providing access to the notebook. 

```
Output:
Access the notebook at http://10.152.183.223/notebook/user-namespace/user-notebook/
```

This command has also a -h or –help  flag which prints out the help description of the command with a list of recommended images for notebooks. For this list we will use the default list from[ jupyter-ui](https://github.com/canonical/notebook-operators/blob/main/charms/jupyter-ui/config.yaml#L27). This list can be subject to a change based on customer needs.
Valid image: is the image which is accessible by DSS and can create a valid jupyter notebook (you can read more about creating valid images in the Documentation section). If the image should support GPU enhanced workloads the image must contain CUDA and cuDNN drivers (or tools needed for Intel GPU based workloads). The image may not contain the MLflow client python library.

### What needs to get done

1. Implement `create-notebook` command which deploys aforementioned components.
2. Implement integration test with Microk8s

### When is the task considered done

1. Command is implemented
2. Tests are passing

**Comment by ca-scribner** [comment]
@DnPlas can you clarify what this command should be creating?  The issue mentions "creates a notebook object from a Kubernetes manifest template" but I think what we planned was to create a `deployment` that deploys a jupyter notebook (creating a `notebook` object means dss also deploys the kubeflow notebooks operator, which I think is out of scope).  Am I misunderstanding this one?

**Comment by ca-scribner** [comment]
As I'm working through this, `user-data` feels really generic for a pvc name.  For now I'm using `dss-notebooks` for the pvc name, but I can easily revert it to `user-data` or anything else

**Comment by misohu** [comment]
The dss create command has been discussed with UX team please check the DSS spec [here ](https://docs.google.com/document/d/1v0wU8TBb-ui6RcjGRbLwA6XFZnWbuiVb2TPmEgwKejY/edit#heading=h.wylzoqh1ph5w) for details about the error messages and parameters.

**Comment by NohaIhab** [comment]
Due to the updates from the UX team, the pending effort for #43 is to add error handling for:
* notebook creation failure (I interpreted this to be `ApiError`)
* dss not correctly initialized
* when notebook image does not exist or is not accessible
* when image is not specified - I added a comment in the spec to question this and @misohu asked the UX team for feedback about it

in addition to changes in the error logs for:
* when a notebook with the same name already exists
* when the notebook name is missing

other comments related to GPU will be discussed in #39
