### ISSUE TITLE
 Implement DSS `remove` command

### ISSUE THREAD

**Issue by DnPlas** [canonical/data-science-stack#32]
### Why it needs to get done

The remove-notebook command removes a specified notebook using the lightkube library and prints "notebook removed" upon completion.

```
dss remove-notebook --name user-notebook
```

### What needs to get done

1. Implement `remove` command which deploys aforementioned components.
2. Implement integration test with Microk8s

### When is the task considered done

1. Command is implemented
2. Tests are passing

**Comment by misohu** [comment]
The dss remove command has been discussed with UX team please check the DSS spec [here ](https://docs.google.com/document/d/1v0wU8TBb-ui6RcjGRbLwA6XFZnWbuiVb2TPmEgwKejY/edit#heading=h.bvvmo5r2r72m) for details about the error messages and parameters.

**Comment by misohu** [comment]
After discussion with UX team the `remove` command should not be blocking meaning the removal can happen after the command is finished. We will use dss list to check the status of the notebook.
