### ISSUE TITLE
Implement DSS `purge` command

### ISSUE THREAD

**Issue by DnPlas** [canonical/data-science-stack#34]
### Why it needs to get done

The `remove-components` command removes all Kubernetes components connected to DSS. Internally, this involves the removal of the entire `dss` Kubernetes namespace. Importantly, this command does not uninstall the DSS snap or the Python library. It proves useful for reinitialization without the necessity to remove the snap. It's important to note that PVC for notebooks will be removed but data will stay in microk8’s [hostpath folder](https://microk8s.io/docs/addon-hostpath-storage#Customize%20directory%20used%20for%20PersistentVolume).

```
dss remove-components
```

### What needs to get done

1. Implement `remove components` command which deploys aforementioned components.
2. Implement integration test with Microk8s

### When is the task considered done

1. Command is implemented
2. Tests are passing

**Comment by misohu** [comment]
This command has been renamed to `dss purge` more information in [this](https://docs.google.com/document/d/1v0wU8TBb-ui6RcjGRbLwA6XFZnWbuiVb2TPmEgwKejY/edit#heading=h.vzt2qdtc70ug) document

**Comment by misohu** [comment]
After discussion with UX team the `purge` command should  be blocking meaning this command can only finish after the components are completely removed from the cluster. This command should not have a timeout.
