### ISSUE TITLE
Create a workflow for running integration GPU tests

### ISSUE THREAD

**Issue by DnPlas** [canonical/data-science-stack#35]
### Why it needs to get done

The DSS needs to be run in a GPU enabled environment to test the correct integration with GPUs.

### What needs to get done

Create a Github workflow that

1. Provisions a VM with GPUs, it can be either in AWS or self hosted runners
2. Installs all the requirements for testing `dss`
3. Runs integration tests that require GPUs

### When is the task considered done

1. When there is an automated workflow that is triggered on pull and push.

**Comment by orfeas-k** [comment]
Tackled in https://github.com/canonical/data-science-stack/issues/83
