### ISSUE TITLE
Shell logs should be without timestamps and function names

### ISSUE THREAD

**Issue by misohu** [canonical/data-science-stack#77]
### Why it needs to get done

For the shell logs of DSS we don't want to have timestamps and function names included. e.g.
```
2024-04-17 11:04:49 [INFO] [list] [list_notebooks]:
```

### What needs to get done

Rewrite the logging logic not to include this information for shell logs.

### When is the task considered done

Shell logs does not include timestamps and function names.

**Comment by misohu** [comment]
General logging changes:
- for console omit the timestamp and module name + function name 
- for console print to stdout instead of std err 
- for file print with timestamp and module and function
- info warning and error logs should be print to console
- debug should be only print to file 

We use `logger.info` to print the outputs of commands and hints: 
e.g. 
```
logger.info(
      f"Removing the notebook {name}. Check `dss list` for the status of the notebook."
)
```
or 
```
logger.info("Note: You might want to run")
logger.info("  dss status      to check the current status")
logger.info(f"  dss logs {name} to review the notebook logs")
```

We use logger.error to print error messages in modules and in main.
```
logger.error(f"Failed to remove notebook {name}.")
```

We use `logger.debug` to store tracebacks and errors. e.g. (make sure traceback is stored in logsfile)
```
 logger.debug(f"Failed to stop notebook {e}")
 ```

**Comment by NohaIhab** [comment]
thanks @misohu for filing this, I'm keeping the scope of this one to timestamps and function names as the description says, and I filed #87 and #88 to track the changes needed you mentioned in the above comment.
